# Generated by Django 6.1.1 on 2026-10-02 06:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EntryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(max_length=100, unique=True, verbose_name="key"),
                ),
                ("label", models.CharField(max_length=100, verbose_name="label")),
                (
                    "label_plural",
                    models.CharField(max_length=100, verbose_name="plural label"),
                ),
                (
                    "route",
                    models.SlugField(
                        help_text="URL segment of the list, in the site language.",
                        max_length=100,
                        unique=True,
                        verbose_name="route",
                    ),
                ),
                (
                    "colour",
                    models.CharField(
                        default="#000000",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "Use #rrggbb."
                            )
                        ],
                        verbose_name="colour",
                    ),
                ),
                (
                    "tint",
                    models.CharField(
                        blank=True,
                        help_text="Light background; derived from the colour when blank.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "Use #rrggbb."
                            )
                        ],
                        verbose_name="tint",
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=100, verbose_name="icon"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                ("in_menu", models.BooleanField(default=True, verbose_name="in menu")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("thing", "Thing"),
                            ("container_outcome", "Container outcome"),
                            ("container_timespan", "Container timespan"),
                            ("calendar", "Calendar"),
                        ],
                        default="thing",
                        max_length=32,
                        verbose_name="role",
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("media_first", "Media first"),
                            ("gallery", "Gallery"),
                        ],
                        default="article",
                        max_length=32,
                        verbose_name="layout",
                    ),
                ),
                (
                    "allowed_parts",
                    models.JSONField(
                        blank=True, default=list, verbose_name="allowed parts"
                    ),
                ),
                (
                    "required_parts",
                    models.JSONField(
                        blank=True, default=list, verbose_name="required parts"
                    ),
                ),
                (
                    "door_enabled",
                    models.BooleanField(
                        default=False, verbose_name="door on the home page"
                    ),
                ),
                (
                    "door_label",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="door label"
                    ),
                ),
                (
                    "door_pick",
                    models.CharField(
                        choices=[
                            ("latest_featured", "Latest featured"),
                            ("latest", "Latest"),
                            ("upcoming", "Upcoming"),
                            ("random_featured", "Random featured"),
                        ],
                        default="latest_featured",
                        max_length=32,
                        verbose_name="door pick",
                    ),
                ),
                (
                    "door_min_entries",
                    models.PositiveIntegerField(
                        default=1, verbose_name="door minimum entries"
                    ),
                ),
                (
                    "list_filters",
                    models.JSONField(
                        blank=True, default=list, verbose_name="list filters"
                    ),
                ),
                (
                    "has_detail_page",
                    models.BooleanField(default=True, verbose_name="has detail pages"),
                ),
            ],
            options={
                "verbose_name": "content type",
                "verbose_name_plural": "content types",
                "ordering": ["order", "label"],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=100, verbose_name="platform")),
                ("url", models.URLField(verbose_name="URL")),
                ("label", models.CharField(max_length=100, verbose_name="label")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
            ],
            options={
                "verbose_name": "link",
                "verbose_name_plural": "links",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        unique=True, upload_to="assets/%Y/%m/", verbose_name="file"
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        help_text="Required for images; for memes, transcribe the text.",
                        max_length=510,
                        verbose_name="alt text",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "media asset",
                "verbose_name_plural": "media assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, verbose_name="slug")),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "summary",
                    models.CharField(
                        help_text="One sentence for cards and link previews.",
                        max_length=200,
                        verbose_name="summary",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="date")),
                (
                    "start_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="starts"),
                ),
                (
                    "end_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="ends"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="location"
                    ),
                ),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="online"),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Canonical page elsewhere, e.g. itch.io or GitHub.",
                        verbose_name="external page",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("finished", "Finished"),
                            ("abandoned", "Abandoned"),
                        ],
                        max_length=16,
                        verbose_name="outcome",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="featured"),
                ),
                (
                    "hide_from_whats_new",
                    models.BooleanField(
                        default=False, verbose_name="hide from what's new"
                    ),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="license"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                ("search_text", models.TextField(blank=True, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="lapidarium_db.entrytype",
                        verbose_name="type",
                    ),
                ),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="lapidarium_db.mediaasset",
                        verbose_name="cover",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="entries",
                        to="lapidarium_db.tag",
                        verbose_name="tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "entry",
                "verbose_name_plural": "entries",
                "ordering": ["-date", "-start_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("image", "Image"),
                            ("file", "File"),
                            ("link", "Link"),
                        ],
                        default="text",
                        max_length=16,
                        verbose_name="kind",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="Markdown.", verbose_name="text"
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="caption"
                    ),
                ),
                (
                    "options",
                    models.JSONField(blank=True, default=dict, verbose_name="options"),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parts",
                        to="lapidarium_db.mediaasset",
                        verbose_name="file",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="lapidarium_db.entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "part",
                "verbose_name_plural": "parts",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "handle",
                    models.CharField(blank=True, max_length=100, verbose_name="handle"),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="tagline"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Markdown.", verbose_name="bio"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="lapidarium_db.mediaasset",
                        verbose_name="photo",
                    ),
                ),
            ],
            options={"verbose_name": "profile", "verbose_name_plural": "profile"},
        ),
        migrations.CreateModel(
            name="SyndicationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=100, verbose_name="platform")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syndication",
                        to="lapidarium_db.entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "syndication link",
                "verbose_name_plural": "syndication links",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="ExternalItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100, verbose_name="source")),
                (
                    "external_id",
                    models.CharField(max_length=255, verbose_name="external id"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("url", models.URLField(verbose_name="URL")),
                ("published_at", models.DateTimeField(verbose_name="published")),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, verbose_name="thumbnail"),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_items",
                        to="lapidarium_db.entry",
                        verbose_name="entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "external item",
                "verbose_name_plural": "external items",
                "ordering": ["-published_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_id"), name="external_item_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=100, verbose_name="key")),
                ("label", models.CharField(max_length=100, verbose_name="label")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("long_text", "Long text"),
                            ("url", "Url"),
                            ("date", "Date"),
                            ("number", "Number"),
                            ("bool", "Bool"),
                            ("choice", "Choice"),
                            ("relation", "Relation"),
                        ],
                        default="text",
                        max_length=32,
                        verbose_name="kind",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=False, verbose_name="required"),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="For choice fields.",
                        verbose_name="choices",
                    ),
                ),
                (
                    "url_kind",
                    models.CharField(
                        choices=[
                            ("any", "Any"),
                            ("youtube", "Youtube"),
                            ("itch", "Itch"),
                            ("github", "Github"),
                        ],
                        default="any",
                        help_text="For URL fields.",
                        max_length=32,
                        verbose_name="URL validator",
                    ),
                ),
                (
                    "show_on_card",
                    models.BooleanField(default=False, verbose_name="show on card"),
                ),
                (
                    "show_in_metadata_panel",
                    models.BooleanField(
                        default=True, verbose_name="show in metadata panel"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "entry_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="lapidarium_db.entrytype",
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="For relation fields.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lapidarium_db.entrytype",
                        verbose_name="target type",
                    ),
                ),
            ],
            options={
                "verbose_name": "field",
                "verbose_name_plural": "fields",
                "ordering": ["order", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entry_type", "key"), name="field_key_unique_per_type"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.SlugField(max_length=100, verbose_name="role")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "from_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="lapidarium_db.entry",
                    ),
                ),
                (
                    "to_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backlinks",
                        to="lapidarium_db.entry",
                        verbose_name="entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "relation",
                "verbose_name_plural": "relations",
                "ordering": ["order", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_entry", "to_entry", "role"),
                        name="relation_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_entry", models.F("to_entry")), _negated=True
                        ),
                        name="relation_not_to_self",
                        violation_error_message="An entry cannot link to itself.",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.UniqueConstraint(
                fields=("type", "slug"), name="entry_slug_unique_per_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_at__isnull", True),
                    ("start_at__isnull", True),
                    ("end_at__gte", models.F("start_at")),
                    _connector="OR",
                ),
                name="entry_ends_after_start",
                violation_error_message="Ends before it starts.",
            ),
        ),
    ]
