# Generated by Django 6.1.1 on 2026-10-02 08:15

import functools

import django.core.validators
from django.db import migrations, models

import lapidarium.pacts


class Migration(migrations.Migration):

    dependencies = [("lapidarium_db", "0001_content_model")]

    operations = [
        migrations.AlterField(
            model_name="entrytype",
            name="allowed_parts",
            field=models.JSONField(
                blank=True,
                default=functools.partial(list, (lapidarium.pacts.PartKind["TEXT"],)),
                verbose_name="allowed parts",
            ),
        ),
        migrations.AlterField(
            model_name="entrytype",
            name="door_label",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="door label"
            ),
        ),
        migrations.AlterField(
            model_name="entrytype",
            name="icon",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="icon"
            ),
        ),
        migrations.AlterField(
            model_name="entrytype",
            name="tint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Light background; derived from the colour when blank.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "Use #rrggbb."
                    )
                ],
                verbose_name="tint",
            ),
        ),
    ]
